// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjy6Sp20-J1KZl2HA1_VtoRDPOu04x6Hg',
    appId: '1:472955726425:web:150d051876cd16106a5f48',
    messagingSenderId: '472955726425',
    projectId: 'blood-donation-app-e4c67',
    authDomain: 'blood-donation-app-e4c67.firebaseapp.com',
    storageBucket: 'blood-donation-app-e4c67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQsNxpYUNaWLiAH-8KsbzuVU04r773P4U',
    appId: '1:472955726425:android:fd75f5ab410dbc016a5f48',
    messagingSenderId: '472955726425',
    projectId: 'blood-donation-app-e4c67',
    storageBucket: 'blood-donation-app-e4c67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABem80lRRp6xkOCyxLRc2ow8AcjB6w-m0',
    appId: '1:472955726425:ios:e5d55a921f732b7e6a5f48',
    messagingSenderId: '472955726425',
    projectId: 'blood-donation-app-e4c67',
    storageBucket: 'blood-donation-app-e4c67.appspot.com',
    iosClientId: '472955726425-413iea9d2pstvluj9pv7j6vnafhc8lf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABem80lRRp6xkOCyxLRc2ow8AcjB6w-m0',
    appId: '1:472955726425:ios:e5d55a921f732b7e6a5f48',
    messagingSenderId: '472955726425',
    projectId: 'blood-donation-app-e4c67',
    storageBucket: 'blood-donation-app-e4c67.appspot.com',
    iosClientId: '472955726425-413iea9d2pstvluj9pv7j6vnafhc8lf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );
}
